
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package co.gov.dian.servicios.facturaelectronica.reportarfactura;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-17T11:34:38.826-05:00
 * Generated source version: 3.2.7
 *
 */

@javax.jws.WebService(
                      serviceName = "facturaElectronicaPortNameService",
                      portName = "facturaElectronicaPortNameSoap11",
                      targetNamespace = "http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura",
                      wsdlLocation = "file:/C:/Users/kevin/Documents/effectivesoftware/invoice/electonic/src/main/resources/wsdl/facturaElectronica.wsdl",
                      endpointInterface = "co.gov.dian.servicios.facturaelectronica.reportarfactura.FacturaElectronicaPortName")

public class FacturaElectronicaPortNameSoap11Impl implements FacturaElectronicaPortName {

    private static final Logger LOG = Logger.getLogger(FacturaElectronicaPortNameSoap11Impl.class.getName());

    /* (non-Javadoc)
     * @see co.gov.dian.servicios.facturaelectronica.reportarfactura.FacturaElectronicaPortName#envioFacturaElectronica(co.gov.dian.servicios.facturaelectronica.reportarfactura.EnvioFacturaElectronica envioFacturaElectronicaPeticion)*
     */
    public co.gov.dian.servicios.facturaelectronica.reportarfactura.AcuseRecibo envioFacturaElectronica(EnvioFacturaElectronica envioFacturaElectronicaPeticion) {
        LOG.info("Executing operation envioFacturaElectronica");
        System.out.println(envioFacturaElectronicaPeticion);
        try {
            co.gov.dian.servicios.facturaelectronica.reportarfactura.AcuseRecibo _return = new co.gov.dian.servicios.facturaelectronica.reportarfactura.AcuseRecibo();
            co.gov.dian.servicios.facturaelectronica.reportarfactura.ReceivedInvoice _returnReceivedInvoice = new co.gov.dian.servicios.facturaelectronica.reportarfactura.ReceivedInvoice();
            _returnReceivedInvoice.setNumeroFactura("NumeroFactura-1317553995");
            _returnReceivedInvoice.setUUID("UUID-392540336");
            _returnReceivedInvoice.setResponse(-2139905112);
            _returnReceivedInvoice.setComments("Comments-1347153331");
            _return.setReceivedInvoice(_returnReceivedInvoice);
            _return.setVersion("Version1633273443");
            _return.setReceivedDateTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-17T11:34:38.843-05:00"));
            _return.setResponseDateTime(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-17T11:34:38.844-05:00"));
            _return.setResponse(-267228038);
            _return.setComments("Comments657639038");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
