package co.gov.dian.servicios.facturaelectronica.reportarfactura;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-17T11:34:38.902-05:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "facturaElectronicaPortNameService",
                  wsdlLocation = "file:/C:/Users/kevin/Documents/effectivesoftware/invoice/electonic/src/main/resources/wsdl/facturaElectronica.wsdl",
                  targetNamespace = "http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura")
public class FacturaElectronicaPortNameService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura", "facturaElectronicaPortNameService");
    public final static QName FacturaElectronicaPortNameSoap11 = new QName("http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura", "facturaElectronicaPortNameSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/kevin/Documents/effectivesoftware/invoice/electonic/src/main/resources/wsdl/facturaElectronica.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FacturaElectronicaPortNameService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/kevin/Documents/effectivesoftware/invoice/electonic/src/main/resources/wsdl/facturaElectronica.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FacturaElectronicaPortNameService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FacturaElectronicaPortNameService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FacturaElectronicaPortNameService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FacturaElectronicaPortNameService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FacturaElectronicaPortNameService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FacturaElectronicaPortNameService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FacturaElectronicaPortName
     */
    @WebEndpoint(name = "facturaElectronicaPortNameSoap11")
    public FacturaElectronicaPortName getFacturaElectronicaPortNameSoap11() {
        return super.getPort(FacturaElectronicaPortNameSoap11, FacturaElectronicaPortName.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FacturaElectronicaPortName
     */
    @WebEndpoint(name = "facturaElectronicaPortNameSoap11")
    public FacturaElectronicaPortName getFacturaElectronicaPortNameSoap11(WebServiceFeature... features) {
        return super.getPort(FacturaElectronicaPortNameSoap11, FacturaElectronicaPortName.class, features);
    }

}
