
package co.gov.dian.servicios.facturaelectronica.reportarfactura;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.xml.namespace.QName;


import org.apache.wss4j.dom.WSConstants;
import org.apache.wss4j.dom.handler.WSHandlerConstants;

import com.invoice.electonic.security.ClientePasswordCallback;








/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-17T11:34:38.598-05:00
 * Generated source version: 3.2.7
 *
 */
public final class FacturaElectronicaPortName_FacturaElectronicaPortNameSoap11_Client {

    private static final QName SERVICE_NAME = new QName("http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura", "facturaElectronicaPortNameService");

    private FacturaElectronicaPortName_FacturaElectronicaPortNameSoap11_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FacturaElectronicaPortNameService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }

        }

        FacturaElectronicaPortNameService ss = new FacturaElectronicaPortNameService(wsdlURL, SERVICE_NAME);
        FacturaElectronicaPortName port = ss.getFacturaElectronicaPortNameSoap11();
//        
//        Client client = ClientProxy.getClient(port);
//         Endpoint cxfEndpoint = client.getEndpoint();
//        
        
          
          
        Map<String, Object> outProps = new HashMap<String, Object>();
        outProps.put(WSHandlerConstants.ACTION,WSHandlerConstants.USERNAME_TOKEN);
        // Specify our username
        outProps.put(WSHandlerConstants.USER, "54a7fd82-9ea1-498d-9d03-35fc75097a3d");
        // Password type : plain text
        outProps.put(WSHandlerConstants.PASSWORD_TYPE, WSConstants.PW_TEXT);
        // Callback used to retrieve password for given user.
        outProps.put(WSHandlerConstants.ADD_USERNAMETOKEN_NONCE, "true");
        outProps.put(WSHandlerConstants.ADD_USERNAMETOKEN_CREATED, "true");
        outProps.put(WSHandlerConstants.PW_CALLBACK_CLASS,ClientePasswordCallback.class.getName());
        
        
        
        
//        WSS4JOutInterceptor wsOut = new WSS4JOutInterceptor(outProps);
//        cxfEndpoint.getOutInterceptors().add(wsOut);
//        
        

        
        System.out.println("Invoking envioFacturaElectronica...");
        co.gov.dian.servicios.facturaelectronica.reportarfactura.EnvioFacturaElectronica _envioFacturaElectronica_envioFacturaElectronicaPeticion = new co.gov.dian.servicios.facturaelectronica.reportarfactura.EnvioFacturaElectronica();
        _envioFacturaElectronica_envioFacturaElectronicaPeticion.setNIT("76305531");
        _envioFacturaElectronica_envioFacturaElectronicaPeticion.setInvoiceNumber("123");
        _envioFacturaElectronica_envioFacturaElectronicaPeticion.setIssueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar());
        javax.activation.DataHandler _envioFacturaElectronica_envioFacturaElectronicaPeticionDocument = null;
        _envioFacturaElectronica_envioFacturaElectronicaPeticion.setDocument(_envioFacturaElectronica_envioFacturaElectronicaPeticionDocument);
        co.gov.dian.servicios.facturaelectronica.reportarfactura.AcuseRecibo _envioFacturaElectronica__return = port.envioFacturaElectronica(_envioFacturaElectronica_envioFacturaElectronicaPeticion);
        System.out.println("envioFacturaElectronica.result=" + _envioFacturaElectronica__return);


        

        System.exit(0);
    }

}
