
package co.gov.dian.servicios.facturaelectronica.reportarfactura;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-17T11:34:38.598-05:00
 * Generated source version: 3.2.7
 *
 */
public final class FacturaElectronicaPortName_FacturaElectronicaPortNameSoap11_Client {

    private static final QName SERVICE_NAME = new QName("http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura", "facturaElectronicaPortNameService");

    private FacturaElectronicaPortName_FacturaElectronicaPortNameSoap11_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FacturaElectronicaPortNameService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }

        }

        FacturaElectronicaPortNameService ss = new FacturaElectronicaPortNameService(wsdlURL, SERVICE_NAME);
        FacturaElectronicaPortName port = ss.getFacturaElectronicaPortNameSoap11();

        {
        System.out.println("Invoking envioFacturaElectronica...");
        co.gov.dian.servicios.facturaelectronica.reportarfactura.EnvioFacturaElectronica _envioFacturaElectronica_envioFacturaElectronicaPeticion = new co.gov.dian.servicios.facturaelectronica.reportarfactura.EnvioFacturaElectronica();
        _envioFacturaElectronica_envioFacturaElectronicaPeticion.setNIT("NIT1967027343");
        _envioFacturaElectronica_envioFacturaElectronicaPeticion.setInvoiceNumber("InvoiceNumber1098988654");
        _envioFacturaElectronica_envioFacturaElectronicaPeticion.setIssueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-11-17T11:34:38.765-05:00"));
        javax.activation.DataHandler _envioFacturaElectronica_envioFacturaElectronicaPeticionDocument = null;
        _envioFacturaElectronica_envioFacturaElectronicaPeticion.setDocument(_envioFacturaElectronica_envioFacturaElectronicaPeticionDocument);
        co.gov.dian.servicios.facturaelectronica.reportarfactura.AcuseRecibo _envioFacturaElectronica__return = port.envioFacturaElectronica(_envioFacturaElectronica_envioFacturaElectronicaPeticion);
        System.out.println("envioFacturaElectronica.result=" + _envioFacturaElectronica__return);


        }

        System.exit(0);
    }

}
